name: Release the dev extenstion

on: 
  push:
    tags:
    - '^v[0-9]+.[0-9]+.[0-9]+-dev$'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 
    - name: Setup node
      uses: actions/setup-node@master
      with:
        node-version: '18.x'    
    - name: Install dependencies
      run: npm install  
    - name: Build extenstion
      run: npm run build       
    - name: Zip the build
      shell: bash
      run: zip -r build.zip build       
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build.zip"
        generateReleaseNotes: true
        prerelease: true
        