name: Unit Test

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  jest:
    name: Run unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10    
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@master     
      - name: Install dependencies
        run: npm install
      - name: Run Jest unit test
        run: npm run test
